linters:
  enable:
    - gosec 
output: 
  # print lines of code with issue, default is true
  print-issued-lines: false
  # print linter name in the end of issue text, default is true
  print-linter-name: true